# Site settings
title:
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://delilah1004.github.io/sir/" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
